/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AbuseError = { 'invalidInput' : string } |
  { 'notFound' : null };
export interface AccuracyBucket {
  'total' : bigint,
  'correct' : bigint,
  'bucketLabel' : string,
  'accuracyPercent' : number,
}
export interface ActivityItem {
  'at' : Timestamp,
  'title' : string,
  'kind' : string,
}
export interface AiConfigStatus {
  'keyHint' : [] | [string],
  'hasPersonalKey' : boolean,
}
export type AiError = { 'invalidRequest' : string } |
  { 'notConfigured' : null } |
  { 'generationFailed' : string };
export type AiSource = { 'personalKey' : null } |
  { 'platform' : null };
export interface AnalyticsBreakdown {
  'byClass' : Array<AccuracyBucket>,
  'byQuestionType' : Array<AccuracyBucket>,
  'bySubject' : Array<AccuracyBucket>,
}
export type AnswerData = { 'shortAnswer' : { 'expected' : string } } |
  { 'multipleChoice' : { 'correctOptionId' : Id, 'options' : Array<Option> } } |
  { 'trueFalse' : { 'correct' : boolean } };
export interface AnswerFeedback {
  'explanation' : [] | [string],
  'correctAnswer' : AnswerData,
  'correct' : boolean,
}
export interface AttemptSummary {
  'id' : Id,
  'completedAt' : Timestamp,
  'total' : bigint,
  'mode' : SessionMode,
  'scopeLabel' : string,
  'score' : bigint,
}
export interface BreadcrumbItem { 'id' : Id, 'name' : string }
export interface Cell { 'value' : Value, 'name' : string }
export interface ChapterDetail {
  'topics' : Array<TopicSummary>,
  'chapter' : ChapterSummary,
}
export interface ChapterSummary {
  'id' : Id,
  'topicCount' : bigint,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : [] | [string],
  'updatedAt' : Timestamp,
  'subjectId' : Id,
}
export interface ClassDetail {
  'subjects' : Array<SubjectSummary>,
  'class' : ClassSummary,
}
export interface ClassSummary {
  'id' : Id,
  'subjectCount' : bigint,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : [] | [string],
  'updatedAt' : Timestamp,
}
export type CreateLinkError = { 'invalidUrl' : string } |
  { 'rateLimited' : null };
export interface CreatedLink {
  'id' : LinkId,
  'status' : LinkStatus,
  'code' : ShortCode,
  'createdAt' : Timestamp,
  'targetUrl' : string,
  'editToken' : EditToken,
  'manageUrl' : string,
  'shortUrl' : string,
}
export interface DailyScanCount { 'day' : string, 'count' : bigint }
export interface DashboardStats {
  'topicCount' : bigint,
  'subjectCount' : bigint,
  'classCount' : bigint,
  'chapterCount' : bigint,
  'questionCount' : bigint,
}
export type DeviceType = { 'desktop' : null } |
  { 'other' : null } |
  { 'tablet' : null } |
  { 'mobile' : null };
export interface DraftQuestion {
  'id' : Id,
  'explanation' : [] | [string],
  'answer' : AnswerData,
  'questionType' : QuestionType,
  'prompt' : string,
  'topicId' : Id,
}
export type EditToken = string;
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type ExportError = { 'notAuthorized' : null } |
  { 'empty' : null } |
  { 'notFound' : null };
export interface ExportFile {
  'content' : string,
  'mimeType' : string,
  'filename' : string,
}
export type ExportFormat = { 'csv' : null } |
  { 'pdf' : null };
export interface GenerateRequest {
  'count' : bigint,
  'sourceText' : [] | [string],
  'prompt' : string,
  'topicId' : Id,
}
export interface GenerateResult {
  'source' : AiSource,
  'drafts' : Array<GeneratedDraft>,
}
export interface GeneratedDraft { 'source' : AiSource, 'draft' : DraftQuestion }
export type Id = bigint;
export interface LinkDetail {
  'id' : LinkId,
  'status' : LinkStatus,
  'code' : ShortCode,
  'createdAt' : Timestamp,
  'targetUrl' : string,
  'updatedAt' : Timestamp,
  'shortUrl' : string,
}
export type LinkId = bigint;
export type LinkStatus = { 'deleted' : null } |
  { 'active' : null } |
  { 'paused' : null };
export type ManageLinkError = { 'notAuthorized' : null } |
  { 'invalidUrl' : string } |
  { 'notFound' : null };
export type NoteError = { 'notAuthorized' : null } |
  { 'invalidInput' : string } |
  { 'notFound' : null } |
  { 'staleRevision' : { 'actual' : bigint, 'expected' : bigint } };
export type NoteShareError = { 'notAuthorized' : null } |
  { 'notFound' : null };
export interface NoteShareLink {
  'status' : string,
  'token' : string,
  'noteId' : Id,
  'createdAt' : Timestamp,
}
export interface NoteView {
  'id' : Id,
  'status' : string,
  'documentJson' : string,
  'title' : string,
  'topicLabel' : [] | [string],
  'createdAt' : Timestamp,
  'subjectLabel' : [] | [string],
  'updatedAt' : Timestamp,
  'revision' : bigint,
  'chapterLabel' : [] | [string],
  'deletedAt' : [] | [Timestamp],
}
export interface Option { 'id' : Id, 'text' : string }
export interface PublicQuestion {
  'id' : Id,
  'questionType' : QuestionType,
  'prompt' : string,
  'options' : Array<Option>,
}
export interface Question {
  'id' : Id,
  'explanation' : [] | [string],
  'createdAt' : Timestamp,
  'answer' : AnswerData,
  'questionType' : QuestionType,
  'updatedAt' : Timestamp,
  'prompt' : string,
  'topicId' : Id,
}
export interface QuestionResult {
  'submitted' : [] | [SubmittedAnswer],
  'explanation' : [] | [string],
  'correctAnswer' : AnswerData,
  'correct' : boolean,
  'questionType' : QuestionType,
  'questionId' : Id,
  'prompt' : string,
}
export type QuestionType = { 'shortAnswer' : null } |
  { 'multipleChoice' : null } |
  { 'trueFalse' : null };
export type ResolveResult = { 'redirect' : { 'targetUrl' : string } } |
  { 'unavailable' : UnavailableReason };
export type Result = { 'ok' : AnswerFeedback } |
  { 'err' : SessionError };
export type Result_1 = { 'ok' : SessionView } |
  { 'err' : SessionError };
export type Result_2 = { 'ok' : GenerateResult } |
  { 'err' : AiError };
export type Result_3 = { 'ok' : ExportFile } |
  { 'err' : ExportError };
export type Result_4 = { 'ok' : ShareLink } |
  { 'err' : ShareError };
export type Result_5 = { 'ok' : SessionResult } |
  { 'err' : SessionError };
export type Result_6 = { 'ok' : null } |
  { 'err' : Error };
export interface Result__1 { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export interface ScanStats {
  'perDay' : Array<DailyScanCount>,
  'totalScans' : bigint,
}
export type SessionError = { 'noQuestions' : null } |
  { 'notAuthorized' : null } |
  { 'invalidInput' : string } |
  { 'notFound' : null };
export type SessionMode = { 'practice' : null } |
  { 'timedTest' : null };
export interface SessionQuestion {
  'id' : Id,
  'questionType' : QuestionType,
  'prompt' : string,
  'options' : Array<Option>,
}
export interface SessionResult {
  'id' : Id,
  'completedAt' : Timestamp,
  'startedAt' : Timestamp,
  'total' : bigint,
  'mode' : SessionMode,
  'results' : Array<QuestionResult>,
  'scope' : SessionScope,
  'score' : bigint,
}
export type SessionScope = { 'topic' : Id } |
  { 'chapter' : Id };
export interface SessionView {
  'id' : Id,
  'startedAt' : Timestamp,
  'expiresAt' : [] | [Timestamp],
  'mode' : SessionMode,
  'scopeLabel' : string,
  'scope' : SessionScope,
  'durationSeconds' : [] | [bigint],
  'questions' : Array<SessionQuestion>,
}
export type SettingsError = { 'notAuthorized' : null } |
  { 'invalidInput' : string };
export type ShareError = { 'notAuthorized' : null } |
  { 'notFound' : null };
export interface ShareLink {
  'token' : string,
  'createdAt' : Timestamp,
  'target' : ShareTarget,
}
export type ShareTarget = { 'topic' : Id } |
  { 'chapter' : Id };
export interface SharedContent {
  'title' : string,
  'breadcrumb' : Array<BreadcrumbItem>,
  'questions' : Array<PublicQuestion>,
}
export interface SharedNote {
  'documentJson' : string,
  'title' : string,
  'updatedAt' : Timestamp,
  'revision' : bigint,
}
export type ShortCode = string;
export interface StartSessionRequest {
  'mode' : SessionMode,
  'scope' : SessionScope,
  'durationSeconds' : [] | [bigint],
  'questionCount' : [] | [bigint],
}
export interface SubjectDetail {
  'subject' : SubjectSummary,
  'chapters' : Array<ChapterSummary>,
}
export interface SubjectSummary {
  'id' : Id,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : [] | [string],
  'classId' : Id,
  'updatedAt' : Timestamp,
  'chapterCount' : bigint,
}
export interface SubmitAnswerRequest {
  'answer' : SubmittedAnswer,
  'questionId' : Id,
  'sessionId' : Id,
}
export type SubmittedAnswer = { 'shortAnswer' : { 'text' : string } } |
  { 'multipleChoice' : { 'optionId' : Id } } |
  { 'trueFalse' : { 'value' : boolean } };
export type Timestamp = bigint;
export interface TopicDetail {
  'topic' : TopicSummary,
  'questions' : Array<Question>,
}
export interface TopicPath {
  'topic' : BreadcrumbItem,
  'subject' : BreadcrumbItem,
  'class' : BreadcrumbItem,
  'chapter' : BreadcrumbItem,
}
export interface TopicSummary {
  'id' : Id,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : [] | [string],
  'chapterId' : Id,
  'updatedAt' : Timestamp,
  'questionCount' : bigint,
}
export type UnavailableReason = { 'deleted' : null } |
  { 'notFound' : null } |
  { 'rateLimited' : null } |
  { 'paused' : null };
export interface UserDataExport {
  'content' : string,
  'mimeType' : string,
  'filename' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSettingsView {
  'displayName' : string,
  'dailyTarget' : bigint,
  'appearance' : string,
  'updatedAt' : Timestamp,
  'studyGoal' : string,
}
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result_6>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  /**
   * / Accept an AI-generated draft into a topic's question bank.
   */
  'acceptDraft' : ActorMethod<[Id, DraftQuestion], [] | [Question]>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Finish a session (or let a timed test auto-submit) and record its result.
   */
  'completeSession' : ActorMethod<[Id], Result_5>,
  /**
   * / Create a chapter inside a subject.
   */
  'createChapter' : ActorMethod<
    [Id, string, [] | [string]],
    [] | [ChapterSummary]
  >,
  /**
   * / Create a class.
   */
  'createClass' : ActorMethod<[string, [] | [string]], ClassSummary>,
  /**
   * / Create a short link for a target URL. Anonymous callers are allowed.
   * / Returns the short URL to encode in the QR code and the secret manage URL.
   */
  'createLink' : ActorMethod<
    [string],
    { 'ok' : CreatedLink } |
      { 'err' : CreateLinkError }
  >,
  /**
   * / Create a note owned by the caller.
   */
  'createNote' : ActorMethod<
    [string, [] | [string], [] | [string], [] | [string], string, string],
    NoteView
  >,
  /**
   * / Create a read-only share token for one of the caller's notes.
   */
  'createNoteShare' : ActorMethod<
    [Id],
    { 'ok' : NoteShareLink } |
      { 'err' : NoteShareError }
  >,
  /**
   * / Create a question inside a topic.
   */
  'createQuestion' : ActorMethod<
    [Id, string, QuestionType, AnswerData, [] | [string]],
    [] | [Question]
  >,
  /**
   * / Create (or return the existing) public read-only share link for a
   * / chapter or topic.
   */
  'createShare' : ActorMethod<[ShareTarget], Result_4>,
  /**
   * / Create a subject inside a class.
   */
  'createSubject' : ActorMethod<
    [Id, string, [] | [string]],
    [] | [SubjectSummary]
  >,
  /**
   * / Create a topic inside a chapter.
   */
  'createTopic' : ActorMethod<[Id, string, [] | [string]], [] | [TopicSummary]>,
  /**
   * / Delete a chapter and all of its descendants.
   */
  'deleteChapter' : ActorMethod<[Id], boolean>,
  /**
   * / Delete a class and all of its descendants.
   */
  'deleteClass' : ActorMethod<[Id], boolean>,
  /**
   * / Soft-delete a link by secret edit token.
   */
  'deleteLink' : ActorMethod<
    [EditToken],
    { 'ok' : null } |
      { 'err' : ManageLinkError }
  >,
  /**
   * / Delete a question.
   */
  'deleteQuestion' : ActorMethod<[Id], boolean>,
  /**
   * / Delete a subject and all of its descendants.
   */
  'deleteSubject' : ActorMethod<[Id], boolean>,
  /**
   * / Delete a topic and all of its questions.
   */
  'deleteTopic' : ActorMethod<[Id], boolean>,
  'execute' : ActorMethod<[string], Result__1>,
  /**
   * / Export a topic or chapter as a downloadable file.
   */
  'exportContent' : ActorMethod<[ShareTarget, ExportFormat], Result_3>,
  /**
   * / Export everything the caller stores as a downloadable JSON file.
   */
  'exportMyData' : ActorMethod<[], UserDataExport>,
  /**
   * / Generate draft questions for a topic.
   */
  'generateDrafts' : ActorMethod<[GenerateRequest], Result_2>,
  /**
   * / The caller's AI configuration state. Never returns the saved key.
   */
  'getAiConfig' : ActorMethod<[], AiConfigStatus>,
  /**
   * / Accuracy breakdowns by class, subject, and question type.
   */
  'getAnalyticsBreakdown' : ActorMethod<[], AnalyticsBreakdown>,
  /**
   * / Static Markdown documentation of this backend's public API.
   */
  'getApiDoc' : ActorMethod<[], string>,
  /**
   * / Practice and test attempt history, newest first.
   */
  'getAttemptHistory' : ActorMethod<[], Array<AttemptSummary>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Detail view of a chapter with its topics.
   */
  'getChapter' : ActorMethod<[Id], [] | [ChapterDetail]>,
  /**
   * / Detail view of a class with its subjects.
   */
  'getClass' : ActorMethod<[Id], [] | [ClassDetail]>,
  /**
   * / Dashboard stat cards for the caller.
   */
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  /**
   * / Fetch link details by secret edit token. Anonymous, token-gated.
   */
  'getLinkByToken' : ActorMethod<[EditToken], [] | [LinkDetail]>,
  /**
   * / Read the caller's settings.
   */
  'getMySettings' : ActorMethod<[], [] | [UserSettingsView]>,
  /**
   * / Read one of the caller's notes.
   */
  'getNote' : ActorMethod<[Id], [] | [NoteView]>,
  /**
   * / Recent activity feed for the caller, newest first.
   */
  'getRecentActivity' : ActorMethod<[bigint], Array<ActivityItem>>,
  /**
   * / Scan statistics for a link by secret edit token.
   */
  'getScanStats' : ActorMethod<[EditToken], [] | [ScanStats]>,
  /**
   * / Fetch a live session, including its questions (answers withheld).
   */
  'getSession' : ActorMethod<[Id], [] | [SessionView]>,
  /**
   * / Fetch a recorded session result.
   */
  'getSessionResult' : ActorMethod<[Id], [] | [SessionResult]>,
  /**
   * / Resolve a share token to its public read-only content. Anonymous callers
   * / are allowed; answers are never revealed.
   */
  'getSharedContent' : ActorMethod<[string], [] | [SharedContent]>,
  /**
   * / Resolve a share token to its public read-only note payload.
   */
  'getSharedNote' : ActorMethod<[string], [] | [SharedNote]>,
  /**
   * / Detail view of a subject with its chapters.
   */
  'getSubject' : ActorMethod<[Id], [] | [SubjectDetail]>,
  /**
   * / Detail view of a topic with its questions.
   */
  'getTopic' : ActorMethod<[Id], [] | [TopicDetail]>,
  /**
   * / The class > subject > chapter > topic breadcrumb path for a topic.
   */
  'getTopicPath' : ActorMethod<[Id], [] | [TopicPath]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / List every chapter of a subject.
   */
  'listChapters' : ActorMethod<[Id], Array<ChapterSummary>>,
  /**
   * / List every class owned by the caller.
   */
  'listClasses' : ActorMethod<[], Array<ClassSummary>>,
  /**
   * / List the caller's note share tokens.
   */
  'listNoteShares' : ActorMethod<[], Array<NoteShareLink>>,
  /**
   * / List the caller's live notes, optionally filtered by a search query.
   */
  'listNotes' : ActorMethod<[[] | [string]], Array<NoteView>>,
  /**
   * / List every question in a topic.
   */
  'listQuestions' : ActorMethod<[Id], Array<Question>>,
  /**
   * / List the caller's share links.
   */
  'listShares' : ActorMethod<[], Array<ShareLink>>,
  /**
   * / List every subject of a class.
   */
  'listSubjects' : ActorMethod<[Id], Array<SubjectSummary>>,
  /**
   * / List every topic of a chapter.
   */
  'listTopics' : ActorMethod<[Id], Array<TopicSummary>>,
  /**
   * / List the caller's soft-deleted notes.
   */
  'listTrashedNotes' : ActorMethod<[], Array<NoteView>>,
  /**
   * / Permanently delete one of the caller's notes and its share tokens.
   */
  'permanentlyDeleteNote' : ActorMethod<
    [Id],
    { 'ok' : null } |
      { 'err' : NoteError }
  >,
  /**
   * / Recompute both hot-path indexes from the primary maps.
   * /
   * / The indexes are maintained by the ordinary mutation points (questions in
   * / createQuestion/deleteQuestion/deleteQuestionsOfTopic, link codes in
   * / createLink), so this only ever needs to run once — after an upgrade that
   * / introduces an index onto a state that predates it. Admin-gated because
   * / a full rebuild is the one O(n) operation the indexes exist to avoid.
   */
  'rebuildIndexes' : ActorMethod<[], undefined>,
  /**
   * / Remove the caller's personal OpenAI key.
   */
  'removeAiKey' : ActorMethod<[], AiConfigStatus>,
  /**
   * / Rename (and optionally re-describe) a chapter.
   */
  'renameChapter' : ActorMethod<
    [Id, string, [] | [string]],
    [] | [ChapterSummary]
  >,
  /**
   * / Rename (and optionally re-describe) a class.
   */
  'renameClass' : ActorMethod<[Id, string, [] | [string]], [] | [ClassSummary]>,
  /**
   * / Rename one of the caller's notes.
   */
  'renameNote' : ActorMethod<
    [Id, string],
    { 'ok' : NoteView } |
      { 'err' : NoteError }
  >,
  /**
   * / Rename (and optionally re-describe) a subject.
   */
  'renameSubject' : ActorMethod<
    [Id, string, [] | [string]],
    [] | [SubjectSummary]
  >,
  /**
   * / Rename (and optionally re-describe) a topic.
   */
  'renameTopic' : ActorMethod<[Id, string, [] | [string]], [] | [TopicSummary]>,
  /**
   * / Report a short link as abusive. Anonymous callers are allowed; the
   * / report is rate limited per caller. The throttle rides `#invalidInput`
   * / because that is the only `AbuseError` variant that carries a sentence —
   * / the candid union is generated and gains no variants (the same rule the
   * / Postgres path follows).
   */
  'reportAbuse' : ActorMethod<
    [ShortCode, string],
    { 'ok' : null } |
      { 'err' : AbuseError }
  >,
  /**
   * / Resolve a short code for redirect. Anonymous callers are allowed.
   * / Returns the current target URL or the reason the link is unavailable.
   */
  'resolveCode' : ActorMethod<
    [ShortCode, DeviceType, [] | [string]],
    ResolveResult
  >,
  /**
   * / Restore one of the caller's soft-deleted notes.
   */
  'restoreNote' : ActorMethod<
    [Id],
    { 'ok' : NoteView } |
      { 'err' : NoteError }
  >,
  /**
   * / Revoke one of the caller's note share tokens.
   */
  'revokeNoteShare' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : NoteShareError }
  >,
  /**
   * / Revoke a share link; it no longer resolves afterwards.
   */
  'revokeShare' : ActorMethod<[string], boolean>,
  /**
   * / Save (or replace) the caller's personal OpenAI key.
   */
  'saveAiKey' : ActorMethod<[string], AiConfigStatus>,
  /**
   * / Save the caller's settings.
   */
  'saveMySettings' : ActorMethod<
    [string, string, bigint, string],
    { 'ok' : UserSettingsView } |
      { 'err' : SettingsError }
  >,
  'schema' : ActorMethod<[], string>,
  /**
   * / Pause or unpause a link by secret edit token.
   */
  'setPaused' : ActorMethod<
    [EditToken, boolean],
    { 'ok' : LinkDetail } |
      { 'err' : ManageLinkError }
  >,
  /**
   * / Soft-delete one of the caller's notes.
   */
  'softDeleteNote' : ActorMethod<
    [Id],
    { 'ok' : NoteView } |
      { 'err' : NoteError }
  >,
  /**
   * / Start a practice session or timed test on a topic or chapter.
   */
  'startSession' : ActorMethod<[StartSessionRequest], Result_1>,
  /**
   * / Submit one answer and receive immediate feedback.
   */
  'submitAnswer' : ActorMethod<[SubmitAnswerRequest], Result>,
  /**
   * / Update one of the caller's notes, rejecting a stale `expectedRevision`.
   */
  'updateNote' : ActorMethod<
    [
      Id,
      string,
      [] | [string],
      [] | [string],
      [] | [string],
      string,
      string,
      bigint,
    ],
    { 'ok' : NoteView } |
      { 'err' : NoteError }
  >,
  /**
   * / Edit an existing question.
   */
  'updateQuestion' : ActorMethod<
    [Id, string, QuestionType, AnswerData, [] | [string]],
    [] | [Question]
  >,
  /**
   * / Change the target URL of a link by secret edit token.
   */
  'updateTarget' : ActorMethod<
    [EditToken, string],
    { 'ok' : LinkDetail } |
      { 'err' : ManageLinkError }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];