/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result_6 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const Id = IDL.Nat;
export const Option = IDL.Record({ 'id' : Id, 'text' : IDL.Text });
export const AnswerData = IDL.Variant({
  'shortAnswer' : IDL.Record({ 'expected' : IDL.Text }),
  'multipleChoice' : IDL.Record({
    'correctOptionId' : Id,
    'options' : IDL.Vec(Option),
  }),
  'trueFalse' : IDL.Record({ 'correct' : IDL.Bool }),
});
export const QuestionType = IDL.Variant({
  'shortAnswer' : IDL.Null,
  'multipleChoice' : IDL.Null,
  'trueFalse' : IDL.Null,
});
export const DraftQuestion = IDL.Record({
  'id' : Id,
  'explanation' : IDL.Opt(IDL.Text),
  'answer' : AnswerData,
  'questionType' : QuestionType,
  'prompt' : IDL.Text,
  'topicId' : Id,
});
export const Timestamp = IDL.Int;
export const Question = IDL.Record({
  'id' : Id,
  'explanation' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'answer' : AnswerData,
  'questionType' : QuestionType,
  'updatedAt' : Timestamp,
  'prompt' : IDL.Text,
  'topicId' : Id,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SessionMode = IDL.Variant({
  'practice' : IDL.Null,
  'timedTest' : IDL.Null,
});
export const SubmittedAnswer = IDL.Variant({
  'shortAnswer' : IDL.Record({ 'text' : IDL.Text }),
  'multipleChoice' : IDL.Record({ 'optionId' : Id }),
  'trueFalse' : IDL.Record({ 'value' : IDL.Bool }),
});
export const QuestionResult = IDL.Record({
  'submitted' : IDL.Opt(SubmittedAnswer),
  'explanation' : IDL.Opt(IDL.Text),
  'correctAnswer' : AnswerData,
  'correct' : IDL.Bool,
  'questionType' : QuestionType,
  'questionId' : Id,
  'prompt' : IDL.Text,
});
export const SessionScope = IDL.Variant({ 'topic' : Id, 'chapter' : Id });
export const SessionResult = IDL.Record({
  'id' : Id,
  'completedAt' : Timestamp,
  'startedAt' : Timestamp,
  'total' : IDL.Nat,
  'mode' : SessionMode,
  'results' : IDL.Vec(QuestionResult),
  'scope' : SessionScope,
  'score' : IDL.Nat,
});
export const SessionError = IDL.Variant({
  'noQuestions' : IDL.Null,
  'notAuthorized' : IDL.Null,
  'invalidInput' : IDL.Text,
  'notFound' : IDL.Null,
});
export const Result_5 = IDL.Variant({
  'ok' : SessionResult,
  'err' : SessionError,
});
export const ChapterSummary = IDL.Record({
  'id' : Id,
  'topicCount' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Opt(IDL.Text),
  'updatedAt' : Timestamp,
  'subjectId' : Id,
});
export const ClassSummary = IDL.Record({
  'id' : Id,
  'subjectCount' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Opt(IDL.Text),
  'updatedAt' : Timestamp,
});
export const LinkId = IDL.Nat;
export const LinkStatus = IDL.Variant({
  'deleted' : IDL.Null,
  'active' : IDL.Null,
  'paused' : IDL.Null,
});
export const ShortCode = IDL.Text;
export const EditToken = IDL.Text;
export const CreatedLink = IDL.Record({
  'id' : LinkId,
  'status' : LinkStatus,
  'code' : ShortCode,
  'createdAt' : Timestamp,
  'targetUrl' : IDL.Text,
  'editToken' : EditToken,
  'manageUrl' : IDL.Text,
  'shortUrl' : IDL.Text,
});
export const CreateLinkError = IDL.Variant({
  'invalidUrl' : IDL.Text,
  'rateLimited' : IDL.Null,
});
export const NoteView = IDL.Record({
  'id' : Id,
  'status' : IDL.Text,
  'documentJson' : IDL.Text,
  'title' : IDL.Text,
  'topicLabel' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'subjectLabel' : IDL.Opt(IDL.Text),
  'updatedAt' : Timestamp,
  'revision' : IDL.Nat,
  'chapterLabel' : IDL.Opt(IDL.Text),
  'deletedAt' : IDL.Opt(Timestamp),
});
export const NoteShareLink = IDL.Record({
  'status' : IDL.Text,
  'token' : IDL.Text,
  'noteId' : Id,
  'createdAt' : Timestamp,
});
export const NoteShareError = IDL.Variant({
  'notAuthorized' : IDL.Null,
  'notFound' : IDL.Null,
});
export const ShareTarget = IDL.Variant({ 'topic' : Id, 'chapter' : Id });
export const ShareLink = IDL.Record({
  'token' : IDL.Text,
  'createdAt' : Timestamp,
  'target' : ShareTarget,
});
export const ShareError = IDL.Variant({
  'notAuthorized' : IDL.Null,
  'notFound' : IDL.Null,
});
export const Result_4 = IDL.Variant({ 'ok' : ShareLink, 'err' : ShareError });
export const SubjectSummary = IDL.Record({
  'id' : Id,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Opt(IDL.Text),
  'classId' : Id,
  'updatedAt' : Timestamp,
  'chapterCount' : IDL.Nat,
});
export const TopicSummary = IDL.Record({
  'id' : Id,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Opt(IDL.Text),
  'chapterId' : Id,
  'updatedAt' : Timestamp,
  'questionCount' : IDL.Nat,
});
export const ManageLinkError = IDL.Variant({
  'notAuthorized' : IDL.Null,
  'invalidUrl' : IDL.Text,
  'notFound' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result__1 = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const ExportFormat = IDL.Variant({ 'csv' : IDL.Null, 'pdf' : IDL.Null });
export const ExportFile = IDL.Record({
  'content' : IDL.Text,
  'mimeType' : IDL.Text,
  'filename' : IDL.Text,
});
export const ExportError = IDL.Variant({
  'notAuthorized' : IDL.Null,
  'empty' : IDL.Null,
  'notFound' : IDL.Null,
});
export const Result_3 = IDL.Variant({ 'ok' : ExportFile, 'err' : ExportError });
export const UserDataExport = IDL.Record({
  'content' : IDL.Text,
  'mimeType' : IDL.Text,
  'filename' : IDL.Text,
});
export const GenerateRequest = IDL.Record({
  'count' : IDL.Nat,
  'sourceText' : IDL.Opt(IDL.Text),
  'prompt' : IDL.Text,
  'topicId' : Id,
});
export const AiSource = IDL.Variant({
  'personalKey' : IDL.Null,
  'platform' : IDL.Null,
});
export const GeneratedDraft = IDL.Record({
  'source' : AiSource,
  'draft' : DraftQuestion,
});
export const GenerateResult = IDL.Record({
  'source' : AiSource,
  'drafts' : IDL.Vec(GeneratedDraft),
});
export const AiError = IDL.Variant({
  'invalidRequest' : IDL.Text,
  'notConfigured' : IDL.Null,
  'generationFailed' : IDL.Text,
});
export const Result_2 = IDL.Variant({ 'ok' : GenerateResult, 'err' : AiError });
export const AiConfigStatus = IDL.Record({
  'keyHint' : IDL.Opt(IDL.Text),
  'hasPersonalKey' : IDL.Bool,
});
export const AccuracyBucket = IDL.Record({
  'total' : IDL.Nat,
  'correct' : IDL.Nat,
  'bucketLabel' : IDL.Text,
  'accuracyPercent' : IDL.Float64,
});
export const AnalyticsBreakdown = IDL.Record({
  'byClass' : IDL.Vec(AccuracyBucket),
  'byQuestionType' : IDL.Vec(AccuracyBucket),
  'bySubject' : IDL.Vec(AccuracyBucket),
});
export const AttemptSummary = IDL.Record({
  'id' : Id,
  'completedAt' : Timestamp,
  'total' : IDL.Nat,
  'mode' : SessionMode,
  'scopeLabel' : IDL.Text,
  'score' : IDL.Nat,
});
export const ChapterDetail = IDL.Record({
  'topics' : IDL.Vec(TopicSummary),
  'chapter' : ChapterSummary,
});
export const ClassDetail = IDL.Record({
  'subjects' : IDL.Vec(SubjectSummary),
  'class' : ClassSummary,
});
export const DashboardStats = IDL.Record({
  'topicCount' : IDL.Nat,
  'subjectCount' : IDL.Nat,
  'classCount' : IDL.Nat,
  'chapterCount' : IDL.Nat,
  'questionCount' : IDL.Nat,
});
export const LinkDetail = IDL.Record({
  'id' : LinkId,
  'status' : LinkStatus,
  'code' : ShortCode,
  'createdAt' : Timestamp,
  'targetUrl' : IDL.Text,
  'updatedAt' : Timestamp,
  'shortUrl' : IDL.Text,
});
export const UserSettingsView = IDL.Record({
  'displayName' : IDL.Text,
  'dailyTarget' : IDL.Nat,
  'appearance' : IDL.Text,
  'updatedAt' : Timestamp,
  'studyGoal' : IDL.Text,
});
export const ActivityItem = IDL.Record({
  'at' : Timestamp,
  'title' : IDL.Text,
  'kind' : IDL.Text,
});
export const DailyScanCount = IDL.Record({
  'day' : IDL.Text,
  'count' : IDL.Nat,
});
export const ScanStats = IDL.Record({
  'perDay' : IDL.Vec(DailyScanCount),
  'totalScans' : IDL.Nat,
});
export const SessionQuestion = IDL.Record({
  'id' : Id,
  'questionType' : QuestionType,
  'prompt' : IDL.Text,
  'options' : IDL.Vec(Option),
});
export const SessionView = IDL.Record({
  'id' : Id,
  'startedAt' : Timestamp,
  'expiresAt' : IDL.Opt(Timestamp),
  'mode' : SessionMode,
  'scopeLabel' : IDL.Text,
  'scope' : SessionScope,
  'durationSeconds' : IDL.Opt(IDL.Nat),
  'questions' : IDL.Vec(SessionQuestion),
});
export const BreadcrumbItem = IDL.Record({ 'id' : Id, 'name' : IDL.Text });
export const PublicQuestion = IDL.Record({
  'id' : Id,
  'questionType' : QuestionType,
  'prompt' : IDL.Text,
  'options' : IDL.Vec(Option),
});
export const SharedContent = IDL.Record({
  'title' : IDL.Text,
  'breadcrumb' : IDL.Vec(BreadcrumbItem),
  'questions' : IDL.Vec(PublicQuestion),
});
export const SharedNote = IDL.Record({
  'documentJson' : IDL.Text,
  'title' : IDL.Text,
  'updatedAt' : Timestamp,
  'revision' : IDL.Nat,
});
export const SubjectDetail = IDL.Record({
  'subject' : SubjectSummary,
  'chapters' : IDL.Vec(ChapterSummary),
});
export const TopicDetail = IDL.Record({
  'topic' : TopicSummary,
  'questions' : IDL.Vec(Question),
});
export const TopicPath = IDL.Record({
  'topic' : BreadcrumbItem,
  'subject' : BreadcrumbItem,
  'class' : BreadcrumbItem,
  'chapter' : BreadcrumbItem,
});
export const NoteError = IDL.Variant({
  'notAuthorized' : IDL.Null,
  'invalidInput' : IDL.Text,
  'notFound' : IDL.Null,
  'staleRevision' : IDL.Record({ 'actual' : IDL.Nat, 'expected' : IDL.Nat }),
});
export const AbuseError = IDL.Variant({
  'invalidInput' : IDL.Text,
  'notFound' : IDL.Null,
});
export const DeviceType = IDL.Variant({
  'desktop' : IDL.Null,
  'other' : IDL.Null,
  'tablet' : IDL.Null,
  'mobile' : IDL.Null,
});
export const UnavailableReason = IDL.Variant({
  'deleted' : IDL.Null,
  'notFound' : IDL.Null,
  'rateLimited' : IDL.Null,
  'paused' : IDL.Null,
});
export const ResolveResult = IDL.Variant({
  'redirect' : IDL.Record({ 'targetUrl' : IDL.Text }),
  'unavailable' : UnavailableReason,
});
export const SettingsError = IDL.Variant({
  'notAuthorized' : IDL.Null,
  'invalidInput' : IDL.Text,
});
export const StartSessionRequest = IDL.Record({
  'mode' : SessionMode,
  'scope' : SessionScope,
  'durationSeconds' : IDL.Opt(IDL.Nat),
  'questionCount' : IDL.Opt(IDL.Nat),
});
export const Result_1 = IDL.Variant({
  'ok' : SessionView,
  'err' : SessionError,
});
export const SubmitAnswerRequest = IDL.Record({
  'answer' : SubmittedAnswer,
  'questionId' : Id,
  'sessionId' : Id,
});
export const AnswerFeedback = IDL.Record({
  'explanation' : IDL.Opt(IDL.Text),
  'correctAnswer' : AnswerData,
  'correct' : IDL.Bool,
});
export const Result = IDL.Variant({
  'ok' : AnswerFeedback,
  'err' : SessionError,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result_6], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'acceptDraft' : IDL.Func([Id, DraftQuestion], [IDL.Opt(Question)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeSession' : IDL.Func([Id], [Result_5], []),
  'createChapter' : IDL.Func(
      [Id, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Opt(ChapterSummary)],
      [],
    ),
  'createClass' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [ClassSummary], []),
  'createLink' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : CreatedLink, 'err' : CreateLinkError })],
      [],
    ),
  'createNote' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
      ],
      [NoteView],
      [],
    ),
  'createNoteShare' : IDL.Func(
      [Id],
      [IDL.Variant({ 'ok' : NoteShareLink, 'err' : NoteShareError })],
      [],
    ),
  'createQuestion' : IDL.Func(
      [Id, IDL.Text, QuestionType, AnswerData, IDL.Opt(IDL.Text)],
      [IDL.Opt(Question)],
      [],
    ),
  'createShare' : IDL.Func([ShareTarget], [Result_4], []),
  'createSubject' : IDL.Func(
      [Id, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Opt(SubjectSummary)],
      [],
    ),
  'createTopic' : IDL.Func(
      [Id, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Opt(TopicSummary)],
      [],
    ),
  'deleteChapter' : IDL.Func([Id], [IDL.Bool], []),
  'deleteClass' : IDL.Func([Id], [IDL.Bool], []),
  'deleteLink' : IDL.Func(
      [EditToken],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : ManageLinkError })],
      [],
    ),
  'deleteQuestion' : IDL.Func([Id], [IDL.Bool], []),
  'deleteSubject' : IDL.Func([Id], [IDL.Bool], []),
  'deleteTopic' : IDL.Func([Id], [IDL.Bool], []),
  'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
  'exportContent' : IDL.Func([ShareTarget, ExportFormat], [Result_3], []),
  'exportMyData' : IDL.Func([], [UserDataExport], ['query']),
  'generateDrafts' : IDL.Func([GenerateRequest], [Result_2], []),
  'getAiConfig' : IDL.Func([], [AiConfigStatus], []),
  'getAnalyticsBreakdown' : IDL.Func([], [AnalyticsBreakdown], []),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getAttemptHistory' : IDL.Func([], [IDL.Vec(AttemptSummary)], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChapter' : IDL.Func([Id], [IDL.Opt(ChapterDetail)], []),
  'getClass' : IDL.Func([Id], [IDL.Opt(ClassDetail)], []),
  'getDashboardStats' : IDL.Func([], [DashboardStats], []),
  'getLinkByToken' : IDL.Func([EditToken], [IDL.Opt(LinkDetail)], ['query']),
  'getMySettings' : IDL.Func([], [IDL.Opt(UserSettingsView)], ['query']),
  'getNote' : IDL.Func([Id], [IDL.Opt(NoteView)], ['query']),
  'getRecentActivity' : IDL.Func([IDL.Nat], [IDL.Vec(ActivityItem)], []),
  'getScanStats' : IDL.Func([EditToken], [IDL.Opt(ScanStats)], ['query']),
  'getSession' : IDL.Func([Id], [IDL.Opt(SessionView)], []),
  'getSessionResult' : IDL.Func([Id], [IDL.Opt(SessionResult)], []),
  'getSharedContent' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(SharedContent)],
      ['query'],
    ),
  'getSharedNote' : IDL.Func([IDL.Text], [IDL.Opt(SharedNote)], ['query']),
  'getSubject' : IDL.Func([Id], [IDL.Opt(SubjectDetail)], []),
  'getTopic' : IDL.Func([Id], [IDL.Opt(TopicDetail)], []),
  'getTopicPath' : IDL.Func([Id], [IDL.Opt(TopicPath)], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listChapters' : IDL.Func([Id], [IDL.Vec(ChapterSummary)], []),
  'listClasses' : IDL.Func([], [IDL.Vec(ClassSummary)], []),
  'listNoteShares' : IDL.Func([], [IDL.Vec(NoteShareLink)], ['query']),
  'listNotes' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Vec(NoteView)], ['query']),
  'listQuestions' : IDL.Func([Id], [IDL.Vec(Question)], []),
  'listShares' : IDL.Func([], [IDL.Vec(ShareLink)], []),
  'listSubjects' : IDL.Func([Id], [IDL.Vec(SubjectSummary)], []),
  'listTopics' : IDL.Func([Id], [IDL.Vec(TopicSummary)], []),
  'listTrashedNotes' : IDL.Func([], [IDL.Vec(NoteView)], ['query']),
  'permanentlyDeleteNote' : IDL.Func(
      [Id],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : NoteError })],
      [],
    ),
  'removeAiKey' : IDL.Func([], [AiConfigStatus], []),
  'renameChapter' : IDL.Func(
      [Id, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Opt(ChapterSummary)],
      [],
    ),
  'renameClass' : IDL.Func(
      [Id, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Opt(ClassSummary)],
      [],
    ),
  'renameNote' : IDL.Func(
      [Id, IDL.Text],
      [IDL.Variant({ 'ok' : NoteView, 'err' : NoteError })],
      [],
    ),
  'renameSubject' : IDL.Func(
      [Id, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Opt(SubjectSummary)],
      [],
    ),
  'renameTopic' : IDL.Func(
      [Id, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Opt(TopicSummary)],
      [],
    ),
  'reportAbuse' : IDL.Func(
      [ShortCode, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : AbuseError })],
      [],
    ),
  'resolveCode' : IDL.Func(
      [ShortCode, DeviceType, IDL.Opt(IDL.Text)],
      [ResolveResult],
      [],
    ),
  'restoreNote' : IDL.Func(
      [Id],
      [IDL.Variant({ 'ok' : NoteView, 'err' : NoteError })],
      [],
    ),
  'revokeNoteShare' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : NoteShareError })],
      [],
    ),
  'revokeShare' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'saveAiKey' : IDL.Func([IDL.Text], [AiConfigStatus], []),
  'saveMySettings' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : UserSettingsView, 'err' : SettingsError })],
      [],
    ),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'setPaused' : IDL.Func(
      [EditToken, IDL.Bool],
      [IDL.Variant({ 'ok' : LinkDetail, 'err' : ManageLinkError })],
      [],
    ),
  'softDeleteNote' : IDL.Func(
      [Id],
      [IDL.Variant({ 'ok' : NoteView, 'err' : NoteError })],
      [],
    ),
  'startSession' : IDL.Func([StartSessionRequest], [Result_1], []),
  'submitAnswer' : IDL.Func([SubmitAnswerRequest], [Result], []),
  'updateNote' : IDL.Func(
      [
        Id,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Nat,
      ],
      [IDL.Variant({ 'ok' : NoteView, 'err' : NoteError })],
      [],
    ),
  'updateQuestion' : IDL.Func(
      [Id, IDL.Text, QuestionType, AnswerData, IDL.Opt(IDL.Text)],
      [IDL.Opt(Question)],
      [],
    ),
  'updateTarget' : IDL.Func(
      [EditToken, IDL.Text],
      [IDL.Variant({ 'ok' : LinkDetail, 'err' : ManageLinkError })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result_6 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const Id = IDL.Nat;
  const Option = IDL.Record({ 'id' : Id, 'text' : IDL.Text });
  const AnswerData = IDL.Variant({
    'shortAnswer' : IDL.Record({ 'expected' : IDL.Text }),
    'multipleChoice' : IDL.Record({
      'correctOptionId' : Id,
      'options' : IDL.Vec(Option),
    }),
    'trueFalse' : IDL.Record({ 'correct' : IDL.Bool }),
  });
  const QuestionType = IDL.Variant({
    'shortAnswer' : IDL.Null,
    'multipleChoice' : IDL.Null,
    'trueFalse' : IDL.Null,
  });
  const DraftQuestion = IDL.Record({
    'id' : Id,
    'explanation' : IDL.Opt(IDL.Text),
    'answer' : AnswerData,
    'questionType' : QuestionType,
    'prompt' : IDL.Text,
    'topicId' : Id,
  });
  const Timestamp = IDL.Int;
  const Question = IDL.Record({
    'id' : Id,
    'explanation' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'answer' : AnswerData,
    'questionType' : QuestionType,
    'updatedAt' : Timestamp,
    'prompt' : IDL.Text,
    'topicId' : Id,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SessionMode = IDL.Variant({
    'practice' : IDL.Null,
    'timedTest' : IDL.Null,
  });
  const SubmittedAnswer = IDL.Variant({
    'shortAnswer' : IDL.Record({ 'text' : IDL.Text }),
    'multipleChoice' : IDL.Record({ 'optionId' : Id }),
    'trueFalse' : IDL.Record({ 'value' : IDL.Bool }),
  });
  const QuestionResult = IDL.Record({
    'submitted' : IDL.Opt(SubmittedAnswer),
    'explanation' : IDL.Opt(IDL.Text),
    'correctAnswer' : AnswerData,
    'correct' : IDL.Bool,
    'questionType' : QuestionType,
    'questionId' : Id,
    'prompt' : IDL.Text,
  });
  const SessionScope = IDL.Variant({ 'topic' : Id, 'chapter' : Id });
  const SessionResult = IDL.Record({
    'id' : Id,
    'completedAt' : Timestamp,
    'startedAt' : Timestamp,
    'total' : IDL.Nat,
    'mode' : SessionMode,
    'results' : IDL.Vec(QuestionResult),
    'scope' : SessionScope,
    'score' : IDL.Nat,
  });
  const SessionError = IDL.Variant({
    'noQuestions' : IDL.Null,
    'notAuthorized' : IDL.Null,
    'invalidInput' : IDL.Text,
    'notFound' : IDL.Null,
  });
  const Result_5 = IDL.Variant({ 'ok' : SessionResult, 'err' : SessionError });
  const ChapterSummary = IDL.Record({
    'id' : Id,
    'topicCount' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Opt(IDL.Text),
    'updatedAt' : Timestamp,
    'subjectId' : Id,
  });
  const ClassSummary = IDL.Record({
    'id' : Id,
    'subjectCount' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Opt(IDL.Text),
    'updatedAt' : Timestamp,
  });
  const LinkId = IDL.Nat;
  const LinkStatus = IDL.Variant({
    'deleted' : IDL.Null,
    'active' : IDL.Null,
    'paused' : IDL.Null,
  });
  const ShortCode = IDL.Text;
  const EditToken = IDL.Text;
  const CreatedLink = IDL.Record({
    'id' : LinkId,
    'status' : LinkStatus,
    'code' : ShortCode,
    'createdAt' : Timestamp,
    'targetUrl' : IDL.Text,
    'editToken' : EditToken,
    'manageUrl' : IDL.Text,
    'shortUrl' : IDL.Text,
  });
  const CreateLinkError = IDL.Variant({
    'invalidUrl' : IDL.Text,
    'rateLimited' : IDL.Null,
  });
  const NoteView = IDL.Record({
    'id' : Id,
    'status' : IDL.Text,
    'documentJson' : IDL.Text,
    'title' : IDL.Text,
    'topicLabel' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'subjectLabel' : IDL.Opt(IDL.Text),
    'updatedAt' : Timestamp,
    'revision' : IDL.Nat,
    'chapterLabel' : IDL.Opt(IDL.Text),
    'deletedAt' : IDL.Opt(Timestamp),
  });
  const NoteShareLink = IDL.Record({
    'status' : IDL.Text,
    'token' : IDL.Text,
    'noteId' : Id,
    'createdAt' : Timestamp,
  });
  const NoteShareError = IDL.Variant({
    'notAuthorized' : IDL.Null,
    'notFound' : IDL.Null,
  });
  const ShareTarget = IDL.Variant({ 'topic' : Id, 'chapter' : Id });
  const ShareLink = IDL.Record({
    'token' : IDL.Text,
    'createdAt' : Timestamp,
    'target' : ShareTarget,
  });
  const ShareError = IDL.Variant({
    'notAuthorized' : IDL.Null,
    'notFound' : IDL.Null,
  });
  const Result_4 = IDL.Variant({ 'ok' : ShareLink, 'err' : ShareError });
  const SubjectSummary = IDL.Record({
    'id' : Id,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Opt(IDL.Text),
    'classId' : Id,
    'updatedAt' : Timestamp,
    'chapterCount' : IDL.Nat,
  });
  const TopicSummary = IDL.Record({
    'id' : Id,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Opt(IDL.Text),
    'chapterId' : Id,
    'updatedAt' : Timestamp,
    'questionCount' : IDL.Nat,
  });
  const ManageLinkError = IDL.Variant({
    'notAuthorized' : IDL.Null,
    'invalidUrl' : IDL.Text,
    'notFound' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result__1 = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const ExportFormat = IDL.Variant({ 'csv' : IDL.Null, 'pdf' : IDL.Null });
  const ExportFile = IDL.Record({
    'content' : IDL.Text,
    'mimeType' : IDL.Text,
    'filename' : IDL.Text,
  });
  const ExportError = IDL.Variant({
    'notAuthorized' : IDL.Null,
    'empty' : IDL.Null,
    'notFound' : IDL.Null,
  });
  const Result_3 = IDL.Variant({ 'ok' : ExportFile, 'err' : ExportError });
  const UserDataExport = IDL.Record({
    'content' : IDL.Text,
    'mimeType' : IDL.Text,
    'filename' : IDL.Text,
  });
  const GenerateRequest = IDL.Record({
    'count' : IDL.Nat,
    'sourceText' : IDL.Opt(IDL.Text),
    'prompt' : IDL.Text,
    'topicId' : Id,
  });
  const AiSource = IDL.Variant({
    'personalKey' : IDL.Null,
    'platform' : IDL.Null,
  });
  const GeneratedDraft = IDL.Record({
    'source' : AiSource,
    'draft' : DraftQuestion,
  });
  const GenerateResult = IDL.Record({
    'source' : AiSource,
    'drafts' : IDL.Vec(GeneratedDraft),
  });
  const AiError = IDL.Variant({
    'invalidRequest' : IDL.Text,
    'notConfigured' : IDL.Null,
    'generationFailed' : IDL.Text,
  });
  const Result_2 = IDL.Variant({ 'ok' : GenerateResult, 'err' : AiError });
  const AiConfigStatus = IDL.Record({
    'keyHint' : IDL.Opt(IDL.Text),
    'hasPersonalKey' : IDL.Bool,
  });
  const AccuracyBucket = IDL.Record({
    'total' : IDL.Nat,
    'correct' : IDL.Nat,
    'bucketLabel' : IDL.Text,
    'accuracyPercent' : IDL.Float64,
  });
  const AnalyticsBreakdown = IDL.Record({
    'byClass' : IDL.Vec(AccuracyBucket),
    'byQuestionType' : IDL.Vec(AccuracyBucket),
    'bySubject' : IDL.Vec(AccuracyBucket),
  });
  const AttemptSummary = IDL.Record({
    'id' : Id,
    'completedAt' : Timestamp,
    'total' : IDL.Nat,
    'mode' : SessionMode,
    'scopeLabel' : IDL.Text,
    'score' : IDL.Nat,
  });
  const ChapterDetail = IDL.Record({
    'topics' : IDL.Vec(TopicSummary),
    'chapter' : ChapterSummary,
  });
  const ClassDetail = IDL.Record({
    'subjects' : IDL.Vec(SubjectSummary),
    'class' : ClassSummary,
  });
  const DashboardStats = IDL.Record({
    'topicCount' : IDL.Nat,
    'subjectCount' : IDL.Nat,
    'classCount' : IDL.Nat,
    'chapterCount' : IDL.Nat,
    'questionCount' : IDL.Nat,
  });
  const LinkDetail = IDL.Record({
    'id' : LinkId,
    'status' : LinkStatus,
    'code' : ShortCode,
    'createdAt' : Timestamp,
    'targetUrl' : IDL.Text,
    'updatedAt' : Timestamp,
    'shortUrl' : IDL.Text,
  });
  const UserSettingsView = IDL.Record({
    'displayName' : IDL.Text,
    'dailyTarget' : IDL.Nat,
    'appearance' : IDL.Text,
    'updatedAt' : Timestamp,
    'studyGoal' : IDL.Text,
  });
  const ActivityItem = IDL.Record({
    'at' : Timestamp,
    'title' : IDL.Text,
    'kind' : IDL.Text,
  });
  const DailyScanCount = IDL.Record({ 'day' : IDL.Text, 'count' : IDL.Nat });
  const ScanStats = IDL.Record({
    'perDay' : IDL.Vec(DailyScanCount),
    'totalScans' : IDL.Nat,
  });
  const SessionQuestion = IDL.Record({
    'id' : Id,
    'questionType' : QuestionType,
    'prompt' : IDL.Text,
    'options' : IDL.Vec(Option),
  });
  const SessionView = IDL.Record({
    'id' : Id,
    'startedAt' : Timestamp,
    'expiresAt' : IDL.Opt(Timestamp),
    'mode' : SessionMode,
    'scopeLabel' : IDL.Text,
    'scope' : SessionScope,
    'durationSeconds' : IDL.Opt(IDL.Nat),
    'questions' : IDL.Vec(SessionQuestion),
  });
  const BreadcrumbItem = IDL.Record({ 'id' : Id, 'name' : IDL.Text });
  const PublicQuestion = IDL.Record({
    'id' : Id,
    'questionType' : QuestionType,
    'prompt' : IDL.Text,
    'options' : IDL.Vec(Option),
  });
  const SharedContent = IDL.Record({
    'title' : IDL.Text,
    'breadcrumb' : IDL.Vec(BreadcrumbItem),
    'questions' : IDL.Vec(PublicQuestion),
  });
  const SharedNote = IDL.Record({
    'documentJson' : IDL.Text,
    'title' : IDL.Text,
    'updatedAt' : Timestamp,
    'revision' : IDL.Nat,
  });
  const SubjectDetail = IDL.Record({
    'subject' : SubjectSummary,
    'chapters' : IDL.Vec(ChapterSummary),
  });
  const TopicDetail = IDL.Record({
    'topic' : TopicSummary,
    'questions' : IDL.Vec(Question),
  });
  const TopicPath = IDL.Record({
    'topic' : BreadcrumbItem,
    'subject' : BreadcrumbItem,
    'class' : BreadcrumbItem,
    'chapter' : BreadcrumbItem,
  });
  const NoteError = IDL.Variant({
    'notAuthorized' : IDL.Null,
    'invalidInput' : IDL.Text,
    'notFound' : IDL.Null,
    'staleRevision' : IDL.Record({ 'actual' : IDL.Nat, 'expected' : IDL.Nat }),
  });
  const AbuseError = IDL.Variant({
    'invalidInput' : IDL.Text,
    'notFound' : IDL.Null,
  });
  const DeviceType = IDL.Variant({
    'desktop' : IDL.Null,
    'other' : IDL.Null,
    'tablet' : IDL.Null,
    'mobile' : IDL.Null,
  });
  const UnavailableReason = IDL.Variant({
    'deleted' : IDL.Null,
    'notFound' : IDL.Null,
    'rateLimited' : IDL.Null,
    'paused' : IDL.Null,
  });
  const ResolveResult = IDL.Variant({
    'redirect' : IDL.Record({ 'targetUrl' : IDL.Text }),
    'unavailable' : UnavailableReason,
  });
  const SettingsError = IDL.Variant({
    'notAuthorized' : IDL.Null,
    'invalidInput' : IDL.Text,
  });
  const StartSessionRequest = IDL.Record({
    'mode' : SessionMode,
    'scope' : SessionScope,
    'durationSeconds' : IDL.Opt(IDL.Nat),
    'questionCount' : IDL.Opt(IDL.Nat),
  });
  const Result_1 = IDL.Variant({ 'ok' : SessionView, 'err' : SessionError });
  const SubmitAnswerRequest = IDL.Record({
    'answer' : SubmittedAnswer,
    'questionId' : Id,
    'sessionId' : Id,
  });
  const AnswerFeedback = IDL.Record({
    'explanation' : IDL.Opt(IDL.Text),
    'correctAnswer' : AnswerData,
    'correct' : IDL.Bool,
  });
  const Result = IDL.Variant({ 'ok' : AnswerFeedback, 'err' : SessionError });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result_6], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'acceptDraft' : IDL.Func([Id, DraftQuestion], [IDL.Opt(Question)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeSession' : IDL.Func([Id], [Result_5], []),
    'createChapter' : IDL.Func(
        [Id, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Opt(ChapterSummary)],
        [],
      ),
    'createClass' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [ClassSummary], []),
    'createLink' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : CreatedLink, 'err' : CreateLinkError })],
        [],
      ),
    'createNote' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
        ],
        [NoteView],
        [],
      ),
    'createNoteShare' : IDL.Func(
        [Id],
        [IDL.Variant({ 'ok' : NoteShareLink, 'err' : NoteShareError })],
        [],
      ),
    'createQuestion' : IDL.Func(
        [Id, IDL.Text, QuestionType, AnswerData, IDL.Opt(IDL.Text)],
        [IDL.Opt(Question)],
        [],
      ),
    'createShare' : IDL.Func([ShareTarget], [Result_4], []),
    'createSubject' : IDL.Func(
        [Id, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Opt(SubjectSummary)],
        [],
      ),
    'createTopic' : IDL.Func(
        [Id, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Opt(TopicSummary)],
        [],
      ),
    'deleteChapter' : IDL.Func([Id], [IDL.Bool], []),
    'deleteClass' : IDL.Func([Id], [IDL.Bool], []),
    'deleteLink' : IDL.Func(
        [EditToken],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : ManageLinkError })],
        [],
      ),
    'deleteQuestion' : IDL.Func([Id], [IDL.Bool], []),
    'deleteSubject' : IDL.Func([Id], [IDL.Bool], []),
    'deleteTopic' : IDL.Func([Id], [IDL.Bool], []),
    'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
    'exportContent' : IDL.Func([ShareTarget, ExportFormat], [Result_3], []),
    'exportMyData' : IDL.Func([], [UserDataExport], ['query']),
    'generateDrafts' : IDL.Func([GenerateRequest], [Result_2], []),
    'getAiConfig' : IDL.Func([], [AiConfigStatus], []),
    'getAnalyticsBreakdown' : IDL.Func([], [AnalyticsBreakdown], []),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getAttemptHistory' : IDL.Func([], [IDL.Vec(AttemptSummary)], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChapter' : IDL.Func([Id], [IDL.Opt(ChapterDetail)], []),
    'getClass' : IDL.Func([Id], [IDL.Opt(ClassDetail)], []),
    'getDashboardStats' : IDL.Func([], [DashboardStats], []),
    'getLinkByToken' : IDL.Func([EditToken], [IDL.Opt(LinkDetail)], ['query']),
    'getMySettings' : IDL.Func([], [IDL.Opt(UserSettingsView)], ['query']),
    'getNote' : IDL.Func([Id], [IDL.Opt(NoteView)], ['query']),
    'getRecentActivity' : IDL.Func([IDL.Nat], [IDL.Vec(ActivityItem)], []),
    'getScanStats' : IDL.Func([EditToken], [IDL.Opt(ScanStats)], ['query']),
    'getSession' : IDL.Func([Id], [IDL.Opt(SessionView)], []),
    'getSessionResult' : IDL.Func([Id], [IDL.Opt(SessionResult)], []),
    'getSharedContent' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(SharedContent)],
        ['query'],
      ),
    'getSharedNote' : IDL.Func([IDL.Text], [IDL.Opt(SharedNote)], ['query']),
    'getSubject' : IDL.Func([Id], [IDL.Opt(SubjectDetail)], []),
    'getTopic' : IDL.Func([Id], [IDL.Opt(TopicDetail)], []),
    'getTopicPath' : IDL.Func([Id], [IDL.Opt(TopicPath)], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listChapters' : IDL.Func([Id], [IDL.Vec(ChapterSummary)], []),
    'listClasses' : IDL.Func([], [IDL.Vec(ClassSummary)], []),
    'listNoteShares' : IDL.Func([], [IDL.Vec(NoteShareLink)], ['query']),
    'listNotes' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Vec(NoteView)], ['query']),
    'listQuestions' : IDL.Func([Id], [IDL.Vec(Question)], []),
    'listShares' : IDL.Func([], [IDL.Vec(ShareLink)], []),
    'listSubjects' : IDL.Func([Id], [IDL.Vec(SubjectSummary)], []),
    'listTopics' : IDL.Func([Id], [IDL.Vec(TopicSummary)], []),
    'listTrashedNotes' : IDL.Func([], [IDL.Vec(NoteView)], ['query']),
    'permanentlyDeleteNote' : IDL.Func(
        [Id],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : NoteError })],
        [],
      ),
    'removeAiKey' : IDL.Func([], [AiConfigStatus], []),
    'renameChapter' : IDL.Func(
        [Id, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Opt(ChapterSummary)],
        [],
      ),
    'renameClass' : IDL.Func(
        [Id, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Opt(ClassSummary)],
        [],
      ),
    'renameNote' : IDL.Func(
        [Id, IDL.Text],
        [IDL.Variant({ 'ok' : NoteView, 'err' : NoteError })],
        [],
      ),
    'renameSubject' : IDL.Func(
        [Id, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Opt(SubjectSummary)],
        [],
      ),
    'renameTopic' : IDL.Func(
        [Id, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Opt(TopicSummary)],
        [],
      ),
    'reportAbuse' : IDL.Func(
        [ShortCode, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : AbuseError })],
        [],
      ),
    'resolveCode' : IDL.Func(
        [ShortCode, DeviceType, IDL.Opt(IDL.Text)],
        [ResolveResult],
        [],
      ),
    'restoreNote' : IDL.Func(
        [Id],
        [IDL.Variant({ 'ok' : NoteView, 'err' : NoteError })],
        [],
      ),
    'revokeNoteShare' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : NoteShareError })],
        [],
      ),
    'revokeShare' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'saveAiKey' : IDL.Func([IDL.Text], [AiConfigStatus], []),
    'saveMySettings' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : UserSettingsView, 'err' : SettingsError })],
        [],
      ),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'setPaused' : IDL.Func(
        [EditToken, IDL.Bool],
        [IDL.Variant({ 'ok' : LinkDetail, 'err' : ManageLinkError })],
        [],
      ),
    'softDeleteNote' : IDL.Func(
        [Id],
        [IDL.Variant({ 'ok' : NoteView, 'err' : NoteError })],
        [],
      ),
    'startSession' : IDL.Func([StartSessionRequest], [Result_1], []),
    'submitAnswer' : IDL.Func([SubmitAnswerRequest], [Result], []),
    'updateNote' : IDL.Func(
        [
          Id,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Nat,
        ],
        [IDL.Variant({ 'ok' : NoteView, 'err' : NoteError })],
        [],
      ),
    'updateQuestion' : IDL.Func(
        [Id, IDL.Text, QuestionType, AnswerData, IDL.Opt(IDL.Text)],
        [IDL.Opt(Question)],
        [],
      ),
    'updateTarget' : IDL.Func(
        [EditToken, IDL.Text],
        [IDL.Variant({ 'ok' : LinkDetail, 'err' : ManageLinkError })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };